POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "chiller2",
  "password": "123"
}

###