POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
    client.global.set("token", response.body);
%}

###

GET http://localhost:8080/user/restaurants/1
Authorization: Bearer {{token}}
Accept: application/json