spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
    username: root
    password: root

jwt:
  token:
    secret: lei4cy5w4ilxytw-topjava-graduation-hs256
    expires: 8640000000
