create table dishes
(
    id            bigint generated by default as identity primary key,
    name          varchar(255),
    price         numeric(19, 2),
    active        boolean,
    restaurant_id bigint references restaurants (id)
);
