create table votes
(
    id            bigint generated by default as identity primary key,
    date          date,
    user_id       bigint references users (id),
    restaurant_id bigint references restaurants (id),
    constraint ux_date_user unique (date, user_id)
);
