create table reviews
(
    id            bigint generated by default as identity primary key,
    rating        int           not null,
    text          varchar(1000),
    date          date          not null,
    user_id       bigint        not null references users (id),
    restaurant_id bigint        not null references restaurants (id),
    constraint ux_user_restaurant unique (user_id, restaurant_id),
    constraint ck_reviews_rating check (rating between 1 and 5)
);
