ALTER TABLE dishes ALTER COLUMN restaurant_id SET NOT NULL;

ALTER TABLE votes ALTER COLUMN date SET NOT NULL;
ALTER TABLE votes ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE votes ALTER COLUMN restaurant_id SET NOT NULL;
